import { Geist, Geist_Mono } from "next/font/google";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

const robotoSans = Roboto({
    variable: "--font-Roboto-sans",
    subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app and my lovely Tailwind",
};

export default function RootLayout({ children }) {
    return (
        <html lang='no'>
            <body
                className={`${robotoSans.className} ${robotoMono.className} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
